name: Quarkus CI

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true
        description: release version
      release:
        type: boolean
        required: true

permissions:
  contents: read
  packages: write

env:
  # all image-related variables must be lowercase
  IMAGE_NAME: ghcr.io/mbernatet/template-quarkus

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
