name: Quarkus CI

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true
      release:
        type: boolean
        required: true

permissions:
  contents: read
  packages: write

env:
  # all image-related variables must be lowercase
  IMAGE_NAME: ghcr.io/mbernatet/template-quarkus

jobs:
  build-push:
    uses: mbernatet/reusable-workflows/.github/workflows/quarkus.yml@main
    with:
      java-version: '11'
      java-native: false
      image-name: ghcr.io/mbernatet/template-quarkus
      image-push: true
    secrets:
      container-registry-username: ${{ github.actor }}
      container-registry-password: ${{ secrets.GITHUB_TOKEN }}
      maven-registry-username: ${{ secrets.BOT_USER_NAME }}
      maven-registry-password: ${{ secrets.BOT_ACCESS_TOKEN }}
