name: Quarkus CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  # all image-related variables must be lowercase
  IMAGE_NAME: ghcr.io/mbernatet/template-quarkus

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: get docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          sep-tags: ','

      - name: Build & push docker image
        run: mvn quarkus:build -B -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
        env:
          QUARKUS_CONTAINER_IMAGE_BUILD: true
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_CONTAINER_IMAGE_GROUP: fr-bod-psd
          QUARKUS_CONTAINER_IMAGE_NAME: catalog-manager
          QUARKUS_CONTAINER_IMAGE_TAG: ${DOCKER_METADATA_OUTPUT_VERSION}
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ secrets.BOT_USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}