name: Quarkus CI

on:
  push:
  workflow_dispatch:
    inputs:
      releaseVersion:
        type: text
        required: false
        description: release version (must follow x.y.z format)
        default: auto
      nextDevelopmentVersion:
        type: text
        required: false
        description: next development version (must follow x.y.z-SNAPSHOT format)
        default: auto

permissions:
  contents: read
  packages: write

env:
  # all image-related variables must be lowercase
  IMAGE_NAME: ghcr.io/mbernatet/template-quarkus

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
